version: '3'

services:
  client:
    build: .
    container_name: sample_client
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app
    tty: true
    networks:
      - ecs-sample-server_default

networks:
  ecs-sample-server_default:
    external: true
